const questionData = {
    0: {
    id:0,
    category: "Rumour",
    title: "Will Elon Musk tweet about Dogecoin this week?",
    photo: "elon.png",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  1: {
    id:1,
    category: "Politics",
    title: "Will Jeb Bush win an Oscar tonight?",
    photo: "oscar.png",
    options: ["Dean Tsaltas", "Naruto Uzumaki", "Tim Horton", "Someone Else"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  2: {
    id:2,
    category: "Gaming",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  3: {
    id:3,
    category: "Other",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  4: {
    id:4,
    category: "Gaming",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  5: {
    id:5,
    category: "Other",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  6: {
    id:6,
    category: "Politics",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  7: {
    id:7,
    category: "Rumour",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  },
  8: {
    id:8,
    category: "Rumour",
    photo: "gamer.png",
    title: "Will Counter Strike 2 announced this month?",
    options: ["Yes", "No"],
    openDate: new Date("2022-01-15"),
    closeDate: new Date("2023-01-15"),
  }
}
;

export default questionData;